apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-manifest
  namespace: argocd
spec:
  project: project-1
  source:
    #directory:
     # include: guestbook-ui-svc.yaml
     # include: '{guestbook-ui-svc.yaml,guestbook-ui-deployment.yaml}'
     # exclude: guestbook-ui-svc.yaml 
    repoURL: https://github.com/varshithakjayappa/argocd-practice.git
    targetRevision: main
    path: guestbook-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    

